spring:
  application:
    name: ${SERVICE_NAME:em-api}

  docker:
    compose:
      enabled: ${DOCKER_COMPOSE_ENABLED:false}

  elasticsearch:
    uris: ${ELASTICSEARCH_SCHEME:http}://${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9200}
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD:secret}
    connection-timeout: 5s
    socket-timeout: 30s


server:
  port: ${SERVER_PORT:8080}


management:
  server:
    port: ${ACTUATOR_PORT:8081}
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,metrics,prometheus}                           # Список доступных эндпоинтов
  metrics:
    tags:
      application: ${spring.application.name}                                                   # Имя приложения для метрик
    distribution:
      percentiles-histogram:
        http.server.requests: true                                                              # Гистограмма для метрик HTTP-запросов
  tracing:
    sampling:
      probability: 1.0                                                                          # Трейсинг для всех запросов
  endpoint:
    health:
      show-details: ${HEALTH_DETAILS_VISIBLE:always}                                            # Детализация информации о здоровье сервиса


eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER_ENABLED:true}                                       # Регистрируем сервис в Eureka
    fetch-registry: ${EUREKA_FETCH_ENABLED:true}                                                # Загружаем список зарегистрированных сервисов
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://em-discovery:8761/eureka/}   # URL-адрес реестра Eureka
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:false}                                                # Используем хостнейм вместо IP
    instance-id: ${EUREKA_INSTANCE_HOSTNAME:em-api}:${server.port}:${random.uuid}            # Уникальный идентификатор инстанса
    lease-renewal-interval-in-seconds: ${EUREKA_HEARTBEAT_INTERVAL:30}                          # Частота отправки heartbeat
    lease-expiration-duration-in-seconds: ${EUREKA_LEASE_EXPIRATION:90}                         # Время, через которое инстанс будет считаться недоступным
    status-page-url: http://${GATEWAY_PUBLIC_HOSTNAME:localhost}:${GATEWAY_PUBLIC_PORT:8080}/api/actuator
    health-check-url: http://${GATEWAY_PUBLIC_HOSTNAME:localhost}:${GATEWAY_PUBLIC_PORT:8080}/api/actuator/health